SIMILARITY_DEFAULT = 0.9
SIMILARITY_EXACT_MATCH = 0.96

# debug settings
DEVELOPMENT_MODE_ACTIVE = True
DEBUG_IMAGE_ACTIVE = True and DEVELOPMENT_MODE_ACTIVE
DEBUG_SIMILARITY_VALUE = False and DEBUG_IMAGE_ACTIVE
BENCHMARK_ACTIVE = False and DEVELOPMENT_MODE_ACTIVE
THREAD_DEBUG_ENABLE = False and DEVELOPMENT_MODE_ACTIVE
